### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by bkrajendra** [Article-Data/Sushant-Singh-Rajput.io#1]
I came to this code on 2nd July, it's really strange that I searched him on Github just to get some clue about his suicide. As everyone knows, he was a great technology geek and used to know to code, I thought I can find something in GitHub and I found your code. Can you explain whats this about?

**Comment by Article-Data** [comment]
Hi Rajendra,

Thank you for your concern.
 
I have my own Article website and I host the pages from GitHub.

You can take a look by clicking on below link which will take you to my Website.
https://Sam-articles.github.io

Regards,
Sami

**Comment by bkrajendra** [comment]
Thank you for the information.
Good Job!  keep it up 👍

**Comment by Article-Data** [comment]
Thank you.

Closing this ticket.
